FROM node:22-alpine AS build 

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build  

FROM nginx:alpine  

COPY --from=build /app/dist /etc/nginx/html

RUN mkdir -p /etc/nginx/ssl
COPY storage.nehsa.net.crt /etc/nginx/ssl/storage_nehsa.crt

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN apk update && apk add tcpdump

EXPOSE 22008

CMD ["nginx", "-g", "daemon off;"]
