FROM node:22-alpine AS build 

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build  

FROM nginx:alpine  

COPY --from=build /app/dist /etc/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 22008

CMD ["nginx", "-g", "daemon off;"]
