from room import Room

class Forest:
    rooms = [
        {
            "id": 22,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [
                {"direction": Room.dirs.south, "id": 10},
                {"direction": Room.dirs.east, "id": 11},
                {"direction": Room.dirs.west, "id": 12},
            ],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 23,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.north, "id": 9}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 24,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.west, "id": 9}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 25,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.east, "id": 9}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 26,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [
                {"direction": Room.dirs.south, "id": 14},
                {"direction": Room.dirs.east, "id": 15},
                {"direction": Room.dirs.west, "id": 16},
            ],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 27,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.north, "id": 13}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 28,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.west, "id": 13}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 29,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.east, "id": 13}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 30,
            "name": "Forest",
            "description": "You are in a forest.  Tall, sparse, fir trees spread out around you in all directions.  Dry sticks snap and rustle and you walk.",
            "exits": [{"direction": Room.dirs.south, "id": 18}],
            "environment": Room.Environments.FOREST,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
    ]
