from room import Room

class TownSmee:
    rooms = [
        {
            "id": 0,
            "name": "Town Smee - Inn",
            "description": "A magestic inn.  The grandest building in town.  Three-storied with a yellow roof.",
            "exits": [{"direction": Room.dirs.east, "id": 18}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 1,
            "name": "Town Smee",
            "description": "You are in a small town.  The buildings are made of wood and the streets are dirt.  There dense jungle to the North.",
            "exits": [
                {"direction": Room.dirs.north, "id": 17},
                {"direction": Room.dirs.east, "id": 19},
                {"direction": Room.dirs.west, "id": 20},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 2,
            "name": "Town Smee - Smithy",
            "description": "A blacksmith's shop.  The air is hot and the only light comes from the forge.",
            "exits": [{"direction": Room.dirs.west, "id": 18}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],            
        },
        {
            "id": 3,
            "name": "Town Smee - Market",
            "description": "A small market.  Loud vendors sell their wares.  The air is thick with the smell of food and drink.",
            "exits": [{"direction": Room.dirs.south, "id": 22}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 4,
            "name": "Town Smee - Town Hall",
            "description": "A small town hall.  Chairs are arranged in rows facing a podium.",
            "exits": [
                {"direction": Room.dirs.north, "id": 21},
                {"direction": Room.dirs.east, "id": 23},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 5,
            "name": "Town Smee - Library",
            "description": "A library with a small collection of scrolls, books, and memoirs.",
            "exits": [{"direction": Room.dirs.west, "id": 22}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
    ]
