from room import Room


class TownSmee:
    rooms = [
        {
            "id": 0,
            "name": "Town Smee - Inn",
            "description": "You are in a majestic inn.  The grandest building in town.  A three-storied building with a yellow roof.",
            "exits": [
                {"direction": Room.dirs.east, "id": 1},
                {"direction": Room.dirs.up, "id": 6},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 1,
            "name": "Town Smee - Town Square",
            "description": "You are in a small town.  The buildings are made of quality wood panels and the streets are dirt.  The place feels kept up and clean.",
            "exits": [
                {"direction": Room.dirs.north, "id": 8},
                {"direction": Room.dirs.east, "id": 3},
                {"direction": Room.dirs.west, "id": 0},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 2,
            "name": "Town Smee - Smithy",
            "description": "A blacksmith's shop.  The air is hot and the only light comes from the forge.",
            "exits": [{"direction": Room.dirs.west, "id": 18}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 3,
            "name": "Town Smee - Market",
            "description": "A small market.  Loud vendors sell their wares.  The air is thick with the smell of food and drink.",
            "exits": [{"direction": Room.dirs.west, "id": 1}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 4,
            "name": "Town Smee - Town Hall",
            "description": "A small town hall.  Chairs are arranged in rows facing a podium.",
            "exits": [
                {"direction": Room.dirs.south, "id": 21},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 5,
            "name": "Town Smee - Library",
            "description": "A library with a small collection of scrolls, books, and memoirs.",
            "exits": [{"direction": Room.dirs.west, "id": 22}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 6,
            "name": "Town Smee - Inn - Second Floor",
            "description": "Two hallways leave off with doors on each side for each guests room.",
            "exits": [
                {"direction": Room.dirs.down, "id": 0},
                {"direction": Room.dirs.up, "id": 0},
            ],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 7,
            "name": "Town Smee - Inn - Third Floor",
            "description": "Two hallways leave off with doors on each side for each guests room.",
            "exits": [{"direction": Room.dirs.down, "id": 6}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 8,
            "name": "Town Smee - Cobblestone Road",
            "description": "A cobblestone road heads north and south.  Storefones are on both sides of the road.",
            "exits": [{"direction": Room.dirs.south, "id": 1}],
            "exits": [{"direction": Room.dirs.north, "id": 4}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
        {
            "id": 9,
            "name": "Town Smee - General Store",
            "description": "Two hallways leave off with doors on each side for each guests room.",
            "exits": [{"direction": Room.dirs.down, "id": 6}],
            "environment": Room.Environments.TOWNSMEE,
            "items": [],
            "hidden_items": [],
            "monsters": [],
            "players": [],
        },
    ]
