from enum import Enum


class EffectsArmorEnum(Enum):
    DEFENCE1 = "defence1"
    DEFENCE2 = "defence2"
    WEAK_BLUNT = "weak_blunt"
    WEAK_SLASH = "weak_slash"
    WEAK_PIERCE = "weak_pierce"
    WEAK_FIRE = "weak_fire"
    WEAK_COLD = "weak_cold"
    WEAK_LIGHTNING = "weak_lightning"
    WEAK_ACID = "weak_acid"
    WEAK_POISON = "weak_poison"
    STRONG_BLUNT = "strong_blunt"
    STRONG_SLASH = "strong_slash"
    STRONG_PIERCE = "strong_pierce"
    STRONG_FIRE = "strong_fire"
    STRONG_COLD = "strong_cold"
    STRONG_LIGHTNING = "strong_lightning"
    STRONG_ACID = "strong_acid"
    STRONG_POISON = "strong_poison"
    DEFENCE3 = "defence3"
    DEFENCE4 = "defence4"
    DEFENCE5 = "defence5"
    DEFENCE6 = "defence6"
    DEFENCE7 = "defence7"
    DEFENCE8 = "defence8"
    DEFENCE9 = "defence9"
    DEFENCE10 = "defence10"
    STRONG_HOLY = "strong_holy"
    STRONG_UNHOLY = "strong_unholy"
    WEAK_HOLY = "weak_holy"
    WEAK_UNHOLY = "weak_unholy"
