from enum import Enum


class EventEnum(Enum):
    NONE = "none"
    DUPLICATE_NAME = "duplicate_name"
    EVENT = "event"
    WELCOME = "welcome"
    ERROR = "error"
    INFO = "info"
    ROOM = "room"
    COMMAND = "command"
    USERNAME_REQUEST = "username_request"
    USERNAME_ANSWER = "username_answer"
    BOOK = "book"
    TIME = "time"
    CHANGE_NAME = "change_name"
    YOU_ATTACK = "you_attack"
    INVENTORY = "inventory"
    ATTACK = "attack"
    HEALTH = "health"
    CLIENT_LIST = "client_list"
    MAP_EVENT = "map_event"
    ROOM_IMAGE = "room_image"
    DIRECTION = "direction"
    ANNOUNCEMENT = "announcement"
    ENVIRONMENT = "environment"
    REST = "rest"
    HELP = "help"
    MONSTER_IMAGE = "monster_image"
    PLAYER_IMAGE = "player_image"
    NPC_IMAGE = "npc_image"
    ITEM_IMAGE = "item_image"
    INVALID_NAME = "invalid_name"
    USERNAME_CHANGED = "username_changed"
    HUNGER = "hunger"
    THIRST = "thirst"
    MOOD_CHANGED = "mood_changed"
    INVALID_TOKEN = "invalid_token"
    PLAYER_CREATE = "player_create"
    PLAYER_CHECK_DUPLICATE = "player_check_duplicate"
