
from core.data.monster_data import MonsterData
from core.data.attributes_data import AttributesData
from core.enums.alignments import AlignmentEnum
from core.enums.monsters import MonsterClassEnum
from core.enums.races import PlayerRaceEnum
from core.interfaces.source_data import SourceInterface


class MonsterSource(SourceInterface):
    """
    This class is used to represent the source data for monsters for
    initalization of the database.
    """

    def get_data(self):
        return [
            MonsterData(
                name=None,
                room_id=None,
                pronoun="it",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A eerie ghoul",
                possible_adjectives=["Eerie"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=100,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.GHOUL.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="it",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A shambling zombie",
                possible_adjectives=["Shambling"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=150,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.ZOMBIE.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Zombie collapses into a heap.",
                entrance_cry="Zombie lurches in.",
                victory_cry="The Zombie groans.",
                flee_cry="Zombie shambles away.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="it",                
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A rattling skeleton",
                possible_adjectives=["Rattling"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=120,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.SKELETON.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Skeleton falls apart.",
                entrance_cry="Skeleton rattles in.",
                victory_cry="The Skeleton clatters.",
                flee_cry="Skeleton rattles away.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="he",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A dark vampire",
                possible_adjectives=["Dark"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=200,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.VAMPIRE.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Vampire disintegrates into dust.",
                entrance_cry="Vampire glides in.",
                victory_cry="The Vampire smiles wickedly.",
                flee_cry="Vampire vanishes into the shadows.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="he",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A ferocious werewolf",
                possible_adjectives=["Ferocious"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=250,
                player_race=PlayerRaceEnum.HUMAN.value,
                player_class=MonsterClassEnum.WEREWOLF.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Werewolf howls in pain.",
                entrance_cry="Werewolf bursts in.",
                victory_cry="The Werewolf growls triumphantly.",
                flee_cry="Werewolf retreats into the forest.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="it",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A haunting ghost",
                possible_adjectives=["Haunting"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=180,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.GHOST.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Ghost fades away.",
                entrance_cry="Ghost appears.",
                victory_cry="The Ghost wails mournfully.",
                flee_cry="Ghost vanishes into thin air.",
            ),
            MonsterData(
                name=None,
                room_id=None,
                pronoun="it",
                title=None,
                alignment=AlignmentEnum.NEUTRAL.value,
                description="A wrapped mummy",
                possible_adjectives=["Wrapped"],
                adjective_chance=70,
                respawn_rate_secs=None,
                wanders=True,
                level=1,
                experience=220,
                player_race=PlayerRaceEnum.UNDEAD.value,
                player_class=MonsterClassEnum.MUMMY.value,
                money=0,
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10
                ),
                directives=[],
                death_cry="Mummy crumbles to dust.",
                entrance_cry="Mummy shuffles in.",
                victory_cry="The Mummy groans.",
                flee_cry="Mummy lumbers away.",
            ),
        ]
