from core.data.attributes_data import AttributesData
from core.data.npc_data import NpcData
from core.enums.alignments import AlignmentEnum
from core.enums.npc_classes import NpcClassEnum
from core.enums.npcs import NpcEnum
from core.enums.pronouns import PronounEnum
from core.enums.races import RaceEnum
from core.interfaces.source_data import SourceInterface
from settings.world_settings import WorldSettings


class NpcSource(SourceInterface):
    """
    This class is used to represent the source data for NPCs for
    initalization of the database.
    """

    def get_data(self):
        return [
            NpcData(
                name="Zofia",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Elder Alchemist",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",                
                description="Zofia is a frail old woman, seated in her chair, gesturing for you to look around her shop in Smee.",
                directives=[
                    f"I exist in {WorldSettings.WORLD_NAME}, in Smee",
                    "potions",
                    "herbs",
                    "alchemy",
                    "I am old and tired.",
                    "I am patronizing",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.ALCHEMIST.value,
                wanders=False,
            ),
            NpcData(
                name="Geoff",
                room_id=None,
                pronoun=PronounEnum.HE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Master Armorer",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Geoff is a large, blond haired behemoth of a man. He's nearly 8 feet tall with limbs the size of tree trunks.  He wears scalemail armor and looks ready for battle at any moment.",
                directives=[
                    f"I only exist in the fantasy world of {WorldSettings.WORLD_NAME}, in the town Smee",
                    "armor",
                    "weapons",
                    "tools",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.ARMORER.value,
                wanders=False,
            ),
            NpcData(
                name="Frederick",
                room_id=None,
                pronoun=PronounEnum.HE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Blacksmith",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Frederick is a large, balding man despite only just becoming an adult. He has serious Azure eyes and a oiled mustache. Frederick is wearing a leather apron, a leather vest, and leather glove that reach past his elbows.",
                directives=[
                    f"I only exist in the fantasy world of {WorldSettings.WORLD_NAME}, in the town Smee",
                    "metals",
                    "weapons",
                    "armor",
                    "blacksmithing",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.BLACKSMITH.value,
                wanders=False,
            ),
            NpcData(
                name="Jaque",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Gardener",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="The gardener of the University. Jaque is an absolutely tiny boy, no wait, woman. Despite wearing only simple white robes or apparent effort, she emanates both power and grace. She welcomes you with a smile when she notices you. As a strict requirement for gardeners at the University, bright orange headgear and gloves are always worn.",
                directives=[
                    f"I only exist in the fantasy world of {WorldSettings.WORLD_NAME}, in the town Smee",
                    "spells",
                    "I am secretly a evil wizard but I don't want anyone to know",
                    "magic",
                    "omens",
                    "weather",
                    "gardening",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.GARDENER.value,
                wanders=False,
            ),
            NpcData(
                name="",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Guard",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="The guard stands alert. While in it's armor, you cannot tell many other details. The armour is standard issue but well-maintained hardened leather with metal plating.",
                directives=[
                    f"I only exist in the fantasy world of {WorldSettings.WORLD_NAME}, in the town Smee",
                    "justice",
                    "women",
                    "cards",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                wanders=True,
                type=NpcEnum.GUARD.value,
            ),
            NpcData(
                name="Agnes",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Healer",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Agnes is a kind woman, tending to the sick and injured.",
                directives=[
                    f"I serve {WorldSettings.WORLD_NAME}, in Clearwater",
                    "healing",
                    "medicine",
                    "charity",
                    "I am always compassionate.",
                    "I am always helpful.",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.HEALER.value,
                wanders=True,
            ),
            NpcData(
                name="Maximus",
                room_id=None,
                pronoun=PronounEnum.HE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Tabby Cat",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Maximus is a wise appearing orange tabby cat.",
                directives=["mice", "birds"],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.MAXIMUS.value,
                wanders=True,
            ),
            NpcData(
                name="Jenny",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Barkeep",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Jenny is a shrewd woman, trading goods and wares in her bustling shop in Dustwind.",
                directives=[
                    f"I trade in {WorldSettings.WORLD_NAME}, in Dustwind",
                    "goods",
                    "wares",
                    "bargaining",
                    "I love a good deal.",
                    "I am always fair.",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.MERCHANT,
                wanders=False,
            ),
            NpcData(
                name="Candie",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Princess",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Princess Candie is a beautiful noble, attending to royal duties in the grand castle of Brighthelm.",
                directives=[
                    f"I rule in {WorldSettings.WORLD_NAME}, in Brighthelm",
                    "politics",
                    "diplomacy",
                    "justice",
                    "I am always regal.",
                    "I am always concerned.",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.PRINCESS.value,
                wanders=False,
            ),
            NpcData(
                name="Stone",
                room_id=None,
                pronoun=PronounEnum.SHE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Sheriff",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Sheriff Stone is a grizzled man, upholding the law in the wild west town of Redemption.",
                directives=[
                    f"I uphold the law in {WorldSettings.WORLD_NAME}, in Redemption",
                    "law",
                    "order",
                    "justice",
                    "I am always stern.",
                    "I am always fair.",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.SHERIFF,
                wanders=False,
            ),
            NpcData(
                name="Got",
                room_id=None,
                pronoun=PronounEnum.HE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Armourer",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Got is a average Fae male of a race you're unsure of. His ears roll back and forth as he speaks. He is wearing a simple tunic and trousers, with a leather apron over it.",
                directives=[
                    "I hide the fact that I'm a thief and act like a vendor.",
                    "change from purchases will be short changed in 30 percent of my transactions",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.THIEF.value,
                wanders=False,
            ),
            NpcData(
                name="Renkath",
                room_id=None,
                pronoun=PronounEnum.HE.value,
                alignment=AlignmentEnum.NEUTRAL.value,
                respawn_rate_secs=None,
                experience=1000,
                money=0,
                race_name=RaceEnum.HUMAN.value,
                class_name=NpcClassEnum.MERCHANT.value,
                title="Archmage",
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
                description="Renkath is a powerful wizard.",
                directives=[
                    f"I study magic in {WorldSettings.WORLD_NAME}",
                    "I am stern but fair",
                    "magic is always the answer",
                    "I think I'm smarter than you",
                ],
                attributes=AttributesData(
                    strength=10, 
                    dexterity=10, 
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                    constitution=10,
                    luck=10,
                    agility=10
                ),
                type=NpcEnum.WIZARD.value,
                wanders=True,
            ),
        ]
