
from core.data.monster_data import MonsterData
from core.interfaces.source_data import SourceInterface


class MonsterSource(SourceInterface):
    """
    This class is used to represent the source data for monsters for
    initalization of the database.
    """

    def get_data(self):
        return [
            MonsterData(
                name="Ghoul",
                pronoun="it",
                type="GHOUL",
                alignment="NEUTRAL",
                description="A eerie ghoul",
                possible_adjectives=["Eerie"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=10,
                damage_potential="1d4",
                experience=100,
                money=0,
                death_cry="Ghoul falls over and dies..",
                entrance_cry="Ghoul wanders in..",
                victory_cry="The Ghoul makes no emotion.",
                flee_cry="Ghoul flees in terror.",
            ),
            MonsterType(
                name="Zombie",
                pronoun="it",
                type="ZOMBIE",
                alignment="NEUTRAL",
                description="A shambling zombie",
                possible_adjectives=["Shambling"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=15,
                damage_potential="1d6",
                experience=150,
                money=0,
                death_cry="Zombie collapses into a heap.",
                entrance_cry="Zombie lurches in.",
                victory_cry="The Zombie groans.",
                flee_cry="Zombie shambles away.",
            ),
            MonsterType(
                name="Skeleton",
                pronoun="it",
                type="SKELETON",
                alignment="NEUTRAL",
                description="A rattling skeleton",
                possible_adjectives=["Rattling"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=12,
                damage_potential="1d5",
                experience=120,
                money=0,
                death_cry="Skeleton falls apart.",
                entrance_cry="Skeleton rattles in.",
                victory_cry="The Skeleton clatters.",
                flee_cry="Skeleton rattles away.",
            ),
            MonsterType(
                name="Vampire",
                pronoun="he",
                type="VAMPIRE",
                alignment="EVIL",
                description="A dark vampire",
                possible_adjectives=["Dark"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=20,
                damage_potential="1d8",
                experience=200,
                money=0,
                death_cry="Vampire disintegrates into dust.",
                entrance_cry="Vampire glides in.",
                victory_cry="The Vampire smiles wickedly.",
                flee_cry="Vampire vanishes into the shadows.",
            ),
            MonsterType(
                name="Werewolf",
                pronoun="he",
                type="WEREWOLF",
                alignment="NEUTRAL",
                description="A ferocious werewolf",
                possible_adjectives=["Ferocious"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=25,
                damage_potential="1d10",
                experience=250,
                money=0,
                death_cry="Werewolf howls in pain.",
                entrance_cry="Werewolf bursts in.",
                victory_cry="The Werewolf growls triumphantly.",
                flee_cry="Werewolf retreats into the forest.",
            ),
            MonsterType(
                name="Ghost",
                pronoun="it",
                type="GHOST",
                alignment="NEUTRAL",
                description="A haunting ghost",
                possible_adjectives=["Haunting"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=18,
                damage_potential="1d7",
                experience=180,
                money=0,
                death_cry="Ghost fades away.",
                entrance_cry="Ghost appears.",
                victory_cry="The Ghost wails mournfully.",
                flee_cry="Ghost vanishes into thin air.",
            ),
            MonsterType(
                name="Mummy",
                pronoun="it",
                type="MUMMY",
                alignment="NEUTRAL",
                description="A wrapped mummy",
                possible_adjectives=["Wrapped"],
                adjective_chance=70,
                respawn_rate_secs=None,
                dead_epoch=None,
                wanders=True,
                hitpoints=22,
                damage_potential="1d9",
                experience=220,
                money=0,
                death_cry="Mummy crumbles to dust.",
                entrance_cry="Mummy shuffles in.",
                victory_cry="The Mummy groans.",
                flee_cry="Mummy lumbers away.",
            ),
        ]
