from core.data.attributes_data import AttributesData
from core.data.player_class_data import PlayerClassData
from core.enums.monsters import MonsterClassEnum
from core.enums.npc_classes import NpcClassEnum
from core.enums.player_class_abilities import PlayerClassAbilityEnum
from core.enums.player_classes import PlayerClassEnum
from core.interfaces.source_data import SourceInterface


class PlayerClassSource(SourceInterface):
    """
    This class is used to represent the source data for player classes for
    initalization of the database.
    """

    def get_data(self):
        return [
            PlayerClassData(
                PlayerClassEnum.BARBARIAN.value,
                "A fierce warrior relying on brute strength and rage.",
                [PlayerClassAbilityEnum.MARTIAL_PROWESS],
                directives=["savage", "wild"],
                base_experience_adjustment=350,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.BARD.value,
                "A charismatic musician and storyteller, skilled in both combat and magic.",
                [
                    PlayerClassAbilityEnum.CHARM,
                    PlayerClassAbilityEnum.SUPPORT_MAGIC,
                    PlayerClassAbilityEnum.PLAY_MUSIC,
                    PlayerClassAbilityEnum.PERFORMANCE,
                    PlayerClassAbilityEnum.ILLUSION_MAGIC,
                ],
                directives=["charming", "entertaining"],
                base_experience_adjustment=250,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.BERSERKER.value,
                "An uncontrollable warrior filled with rage and bloodlust.",
                [PlayerClassAbilityEnum.FRENZY, PlayerClassAbilityEnum.MARTIAL_PROWESS],
                directives=["frenzied", "unstable"],
                base_experience_adjustment=400,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.CLERIC.value,
                "A divine caster, channeling the power of their deity.",
                [PlayerClassAbilityEnum.HEALING, PlayerClassAbilityEnum.DIVINE_MAGIC],
                directives=["pious", "devout"],
                base_experience_adjustment=200,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.DRUID.value,
                "A nature-attuned caster, commanding the forces of the wild.",
                [PlayerClassAbilityEnum.NATURE_MAGIC, PlayerClassAbilityEnum.SHAPE_SHIFTING],
                directives=["earthy", "wild"],
                base_experience_adjustment=220,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.KNIGHT.value,
                "A heavily armored warrior, sworn to protect the realm.",
                [PlayerClassAbilityEnum.DEFENSE, PlayerClassAbilityEnum.MARTIAL_PROWESS],
                directives=["noble", "chivalrous"],
                base_experience_adjustment=320,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.MAGE.value,
                "A scholarly caster, wielding arcane power with precision.",
                [PlayerClassAbilityEnum.MAGIC],
                directives=["intellectual", "studious"],
                base_experience_adjustment=180,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.RANGER.value,
                "A skilled tracker and survivalist, at home in the wilderness.",
                [PlayerClassAbilityEnum.TRACKING, PlayerClassAbilityEnum.SURVIVAL],
                directives=["outdoorsy", "resourceful"],
                base_experience_adjustment=310,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.ROGUE.value,
                "A stealthy trickster, skilled in deception and subterfuge.",
                [PlayerClassAbilityEnum.STEALTH, PlayerClassAbilityEnum.TRICKERY],
                directives=["sneaky", "cunning"],
                base_experience_adjustment=330,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.THIEF.value,
                "A nimble rogue, specializing in larceny and stealth.",
                [PlayerClassAbilityEnum.STEALTH, PlayerClassAbilityEnum.LOCKPICKING],
                directives=["sneaky", "cunning"],
                base_experience_adjustment=340,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                PlayerClassEnum.WARRIOR.value,
                "A stalwart fighter, skilled in all forms of combat.",
                [PlayerClassAbilityEnum.MARTIAL_PROWESS, PlayerClassAbilityEnum.WEAPON_MASTERY],
                directives=["brave", "strong"],
                base_experience_adjustment=300,
                playable=True,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.GHOUL.value,
                "Ghoul",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.WEREWOLF.value,
                "Werewolf",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.MUMMY.value,
                "MUMMY",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.GHOST.value,
                "Ghost",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.VAMPIRE.value,
                "Vampire",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.SKELETON.value,
                "Skeleton",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                MonsterClassEnum.ZOMBIE.value,
                "A Zombie",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
            PlayerClassData(
                NpcClassEnum.MERCHANT.value,
                "A merchant",
                [],
                directives=[],
                base_experience_adjustment=300,
                playable=False,
                attributes=AttributesData(
                    strength=10,
                    dexterity=10,
                    constitution=10,
                    intelligence=10,
                    wisdom=10,
                    charisma=10,
                ),
            ),
        ]
