name: nehsanet

version: "3.8"
services:
  nehsanet:
    build: .
    ports:
      - "80:80"
      - "443:443"
    image: "nehsa/nehsanet"
    volumes:
    - "/app/node_modules"
    - ".:/app"
    command: "node index.js"

